// Code generated by MockGen. DO NOT EDIT.
// Source: post_handler.go
//
// Generated by this command:
//
//	mockgen -source=post_handler.go -destination=post_handler_mock_test.go -package=handler_test -typed=true
//

// Package handler_test is a generated GoMock package.
package handler_test

import (
	reflect "reflect"

	model "github.com/nix-united/golang-gin-boilerplate/internal/model"
	service "github.com/nix-united/golang-gin-boilerplate/internal/service"
	gomock "go.uber.org/mock/gomock"
)

// MockpostService is a mock of postService interface.
type MockpostService struct {
	ctrl     *gomock.Controller
	recorder *MockpostServiceMockRecorder
}

// MockpostServiceMockRecorder is the mock recorder for MockpostService.
type MockpostServiceMockRecorder struct {
	mock *MockpostService
}

// NewMockpostService creates a new mock instance.
func NewMockpostService(ctrl *gomock.Controller) *MockpostService {
	mock := &MockpostService{ctrl: ctrl}
	mock.recorder = &MockpostServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockpostService) EXPECT() *MockpostServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockpostService) Create(post *model.Post) *service.RestError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", post)
	ret0, _ := ret[0].(*service.RestError)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockpostServiceMockRecorder) Create(post any) *MockpostServiceCreateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockpostService)(nil).Create), post)
	return &MockpostServiceCreateCall{Call: call}
}

// MockpostServiceCreateCall wrap *gomock.Call
type MockpostServiceCreateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockpostServiceCreateCall) Return(arg0 *service.RestError) *MockpostServiceCreateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockpostServiceCreateCall) Do(f func(*model.Post) *service.RestError) *MockpostServiceCreateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockpostServiceCreateCall) DoAndReturn(f func(*model.Post) *service.RestError) *MockpostServiceCreateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CreatePost mocks base method.
func (m *MockpostService) CreatePost(title, content string, userID uint) (*model.Post, *service.RestError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePost", title, content, userID)
	ret0, _ := ret[0].(*model.Post)
	ret1, _ := ret[1].(*service.RestError)
	return ret0, ret1
}

// CreatePost indicates an expected call of CreatePost.
func (mr *MockpostServiceMockRecorder) CreatePost(title, content, userID any) *MockpostServiceCreatePostCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePost", reflect.TypeOf((*MockpostService)(nil).CreatePost), title, content, userID)
	return &MockpostServiceCreatePostCall{Call: call}
}

// MockpostServiceCreatePostCall wrap *gomock.Call
type MockpostServiceCreatePostCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockpostServiceCreatePostCall) Return(arg0 *model.Post, arg1 *service.RestError) *MockpostServiceCreatePostCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockpostServiceCreatePostCall) Do(f func(string, string, uint) (*model.Post, *service.RestError)) *MockpostServiceCreatePostCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockpostServiceCreatePostCall) DoAndReturn(f func(string, string, uint) (*model.Post, *service.RestError)) *MockpostServiceCreatePostCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Delete mocks base method.
func (m *MockpostService) Delete(post *model.Post) *service.RestError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", post)
	ret0, _ := ret[0].(*service.RestError)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockpostServiceMockRecorder) Delete(post any) *MockpostServiceDeleteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockpostService)(nil).Delete), post)
	return &MockpostServiceDeleteCall{Call: call}
}

// MockpostServiceDeleteCall wrap *gomock.Call
type MockpostServiceDeleteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockpostServiceDeleteCall) Return(arg0 *service.RestError) *MockpostServiceDeleteCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockpostServiceDeleteCall) Do(f func(*model.Post) *service.RestError) *MockpostServiceDeleteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockpostServiceDeleteCall) DoAndReturn(f func(*model.Post) *service.RestError) *MockpostServiceDeleteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetAll mocks base method.
func (m *MockpostService) GetAll(posts *[]model.Post) *service.RestError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", posts)
	ret0, _ := ret[0].(*service.RestError)
	return ret0
}

// GetAll indicates an expected call of GetAll.
func (mr *MockpostServiceMockRecorder) GetAll(posts any) *MockpostServiceGetAllCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockpostService)(nil).GetAll), posts)
	return &MockpostServiceGetAllCall{Call: call}
}

// MockpostServiceGetAllCall wrap *gomock.Call
type MockpostServiceGetAllCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockpostServiceGetAllCall) Return(arg0 *service.RestError) *MockpostServiceGetAllCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockpostServiceGetAllCall) Do(f func(*[]model.Post) *service.RestError) *MockpostServiceGetAllCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockpostServiceGetAllCall) DoAndReturn(f func(*[]model.Post) *service.RestError) *MockpostServiceGetAllCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetByID mocks base method.
func (m *MockpostService) GetByID(id int, post *model.Post) *service.RestError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id, post)
	ret0, _ := ret[0].(*service.RestError)
	return ret0
}

// GetByID indicates an expected call of GetByID.
func (mr *MockpostServiceMockRecorder) GetByID(id, post any) *MockpostServiceGetByIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockpostService)(nil).GetByID), id, post)
	return &MockpostServiceGetByIDCall{Call: call}
}

// MockpostServiceGetByIDCall wrap *gomock.Call
type MockpostServiceGetByIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockpostServiceGetByIDCall) Return(arg0 *service.RestError) *MockpostServiceGetByIDCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockpostServiceGetByIDCall) Do(f func(int, *model.Post) *service.RestError) *MockpostServiceGetByIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockpostServiceGetByIDCall) DoAndReturn(f func(int, *model.Post) *service.RestError) *MockpostServiceGetByIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Save mocks base method.
func (m *MockpostService) Save(post *model.Post) *service.RestError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", post)
	ret0, _ := ret[0].(*service.RestError)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockpostServiceMockRecorder) Save(post any) *MockpostServiceSaveCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockpostService)(nil).Save), post)
	return &MockpostServiceSaveCall{Call: call}
}

// MockpostServiceSaveCall wrap *gomock.Call
type MockpostServiceSaveCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockpostServiceSaveCall) Return(arg0 *service.RestError) *MockpostServiceSaveCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockpostServiceSaveCall) Do(f func(*model.Post) *service.RestError) *MockpostServiceSaveCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockpostServiceSaveCall) DoAndReturn(f func(*model.Post) *service.RestError) *MockpostServiceSaveCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
