// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=service_mock_test.go -package=user_test -typed=true
//

// Package user_test is a generated GoMock package.
package user_test

import (
	context "context"
	reflect "reflect"

	model "github.com/nix-united/golang-gin-boilerplate/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockuserRepository is a mock of userRepository interface.
type MockuserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockuserRepositoryMockRecorder
}

// MockuserRepositoryMockRecorder is the mock recorder for MockuserRepository.
type MockuserRepositoryMockRecorder struct {
	mock *MockuserRepository
}

// NewMockuserRepository creates a new mock instance.
func NewMockuserRepository(ctrl *gomock.Controller) *MockuserRepository {
	mock := &MockuserRepository{ctrl: ctrl}
	mock.recorder = &MockuserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuserRepository) EXPECT() *MockuserRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockuserRepository) Create(ctx context.Context, user *model.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockuserRepositoryMockRecorder) Create(ctx, user any) *MockuserRepositoryCreateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockuserRepository)(nil).Create), ctx, user)
	return &MockuserRepositoryCreateCall{Call: call}
}

// MockuserRepositoryCreateCall wrap *gomock.Call
type MockuserRepositoryCreateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockuserRepositoryCreateCall) Return(arg0 error) *MockuserRepositoryCreateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockuserRepositoryCreateCall) Do(f func(context.Context, *model.User) error) *MockuserRepositoryCreateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockuserRepositoryCreateCall) DoAndReturn(f func(context.Context, *model.User) error) *MockuserRepositoryCreateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetByEmail mocks base method.
func (m *MockuserRepository) GetByEmail(ctx context.Context, email string) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmail", ctx, email)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmail indicates an expected call of GetByEmail.
func (mr *MockuserRepositoryMockRecorder) GetByEmail(ctx, email any) *MockuserRepositoryGetByEmailCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmail", reflect.TypeOf((*MockuserRepository)(nil).GetByEmail), ctx, email)
	return &MockuserRepositoryGetByEmailCall{Call: call}
}

// MockuserRepositoryGetByEmailCall wrap *gomock.Call
type MockuserRepositoryGetByEmailCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockuserRepositoryGetByEmailCall) Return(arg0 *model.User, arg1 error) *MockuserRepositoryGetByEmailCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockuserRepositoryGetByEmailCall) Do(f func(context.Context, string) (*model.User, error)) *MockuserRepositoryGetByEmailCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockuserRepositoryGetByEmailCall) DoAndReturn(f func(context.Context, string) (*model.User, error)) *MockuserRepositoryGetByEmailCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockpasswordService is a mock of passwordService interface.
type MockpasswordService struct {
	ctrl     *gomock.Controller
	recorder *MockpasswordServiceMockRecorder
}

// MockpasswordServiceMockRecorder is the mock recorder for MockpasswordService.
type MockpasswordServiceMockRecorder struct {
	mock *MockpasswordService
}

// NewMockpasswordService creates a new mock instance.
func NewMockpasswordService(ctrl *gomock.Controller) *MockpasswordService {
	mock := &MockpasswordService{ctrl: ctrl}
	mock.recorder = &MockpasswordServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockpasswordService) EXPECT() *MockpasswordServiceMockRecorder {
	return m.recorder
}

// EncryptPassword mocks base method.
func (m *MockpasswordService) EncryptPassword(password string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EncryptPassword", password)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EncryptPassword indicates an expected call of EncryptPassword.
func (mr *MockpasswordServiceMockRecorder) EncryptPassword(password any) *MockpasswordServiceEncryptPasswordCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EncryptPassword", reflect.TypeOf((*MockpasswordService)(nil).EncryptPassword), password)
	return &MockpasswordServiceEncryptPasswordCall{Call: call}
}

// MockpasswordServiceEncryptPasswordCall wrap *gomock.Call
type MockpasswordServiceEncryptPasswordCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockpasswordServiceEncryptPasswordCall) Return(arg0 string, arg1 error) *MockpasswordServiceEncryptPasswordCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockpasswordServiceEncryptPasswordCall) Do(f func(string) (string, error)) *MockpasswordServiceEncryptPasswordCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockpasswordServiceEncryptPasswordCall) DoAndReturn(f func(string) (string, error)) *MockpasswordServiceEncryptPasswordCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
