// Code generated by MockGen. DO NOT EDIT.
// Source: auth_handler.go
//
// Generated by this command:
//
//	mockgen -source=auth_handler.go -destination=auth_handler_mock_test.go -package=handler_test -typed=true
//

// Package handler_test is a generated GoMock package.
package handler_test

import (
	context "context"
	reflect "reflect"

	model "github.com/nix-united/golang-gin-boilerplate/internal/model"
	request "github.com/nix-united/golang-gin-boilerplate/internal/request"
	gomock "go.uber.org/mock/gomock"
)

// MockuserService is a mock of userService interface.
type MockuserService struct {
	ctrl     *gomock.Controller
	recorder *MockuserServiceMockRecorder
}

// MockuserServiceMockRecorder is the mock recorder for MockuserService.
type MockuserServiceMockRecorder struct {
	mock *MockuserService
}

// NewMockuserService creates a new mock instance.
func NewMockuserService(ctrl *gomock.Controller) *MockuserService {
	mock := &MockuserService{ctrl: ctrl}
	mock.recorder = &MockuserServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuserService) EXPECT() *MockuserServiceMockRecorder {
	return m.recorder
}

// CreateUser mocks base method.
func (m *MockuserService) CreateUser(ctx context.Context, registerRequest request.RegisterRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, registerRequest)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockuserServiceMockRecorder) CreateUser(ctx, registerRequest any) *MockuserServiceCreateUserCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockuserService)(nil).CreateUser), ctx, registerRequest)
	return &MockuserServiceCreateUserCall{Call: call}
}

// MockuserServiceCreateUserCall wrap *gomock.Call
type MockuserServiceCreateUserCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockuserServiceCreateUserCall) Return(arg0 error) *MockuserServiceCreateUserCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockuserServiceCreateUserCall) Do(f func(context.Context, request.RegisterRequest) error) *MockuserServiceCreateUserCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockuserServiceCreateUserCall) DoAndReturn(f func(context.Context, request.RegisterRequest) error) *MockuserServiceCreateUserCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetUserByEmail mocks base method.
func (m *MockuserService) GetUserByEmail(ctx context.Context, email string) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", ctx, email)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockuserServiceMockRecorder) GetUserByEmail(ctx, email any) *MockuserServiceGetUserByEmailCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*MockuserService)(nil).GetUserByEmail), ctx, email)
	return &MockuserServiceGetUserByEmailCall{Call: call}
}

// MockuserServiceGetUserByEmailCall wrap *gomock.Call
type MockuserServiceGetUserByEmailCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockuserServiceGetUserByEmailCall) Return(arg0 *model.User, arg1 error) *MockuserServiceGetUserByEmailCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockuserServiceGetUserByEmailCall) Do(f func(context.Context, string) (*model.User, error)) *MockuserServiceGetUserByEmailCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockuserServiceGetUserByEmailCall) DoAndReturn(f func(context.Context, string) (*model.User, error)) *MockuserServiceGetUserByEmailCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockpasswordService is a mock of passwordService interface.
type MockpasswordService struct {
	ctrl     *gomock.Controller
	recorder *MockpasswordServiceMockRecorder
}

// MockpasswordServiceMockRecorder is the mock recorder for MockpasswordService.
type MockpasswordServiceMockRecorder struct {
	mock *MockpasswordService
}

// NewMockpasswordService creates a new mock instance.
func NewMockpasswordService(ctrl *gomock.Controller) *MockpasswordService {
	mock := &MockpasswordService{ctrl: ctrl}
	mock.recorder = &MockpasswordServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockpasswordService) EXPECT() *MockpasswordServiceMockRecorder {
	return m.recorder
}

// VerifyPassword mocks base method.
func (m *MockpasswordService) VerifyPassword(actual, received string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyPassword", actual, received)
	ret0, _ := ret[0].(error)
	return ret0
}

// VerifyPassword indicates an expected call of VerifyPassword.
func (mr *MockpasswordServiceMockRecorder) VerifyPassword(actual, received any) *MockpasswordServiceVerifyPasswordCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyPassword", reflect.TypeOf((*MockpasswordService)(nil).VerifyPassword), actual, received)
	return &MockpasswordServiceVerifyPasswordCall{Call: call}
}

// MockpasswordServiceVerifyPasswordCall wrap *gomock.Call
type MockpasswordServiceVerifyPasswordCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockpasswordServiceVerifyPasswordCall) Return(arg0 error) *MockpasswordServiceVerifyPasswordCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockpasswordServiceVerifyPasswordCall) Do(f func(string, string) error) *MockpasswordServiceVerifyPasswordCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockpasswordServiceVerifyPasswordCall) DoAndReturn(f func(string, string) error) *MockpasswordServiceVerifyPasswordCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
