name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache-dependency-path: "**/go.sum"
      - name: Setup Swagger
        run: |
          go install github.com/swaggo/swag/cmd/swag@v1.16.2
          swag init -g cmd/service/main.go
      - uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: test
          MYSQL_ROOT_PASSWORD: db_password
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache-dependency-path: "**/go.sum"
      - name: Setup Swagger
        run: |
          go install github.com/swaggo/swag/cmd/swag@v1.16.2
          swag init -g cmd/service/main.go
      - name: Run tests
        run: |
          cp .env.testing.github-ci .env.testing
          go install github.com/pressly/goose/cmd/goose@latest
          goose -dir "./db/migrations" mysql "root:db_password@tcp(localhost:3306)/test?parseTime=true" up
          go test -race ./...

  detect-secrets:
    name: Detect Secrets
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: detect-secrets
        uses: reviewdog/action-detect-secrets@v0.27
        with:
          reporter: github-pr-review
          fail-on-error: true
          detect_secrets_flags: --exclude-files '.*_test\.go$'

  govulncheck:
    name: Run govulncheck
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache-dependency-path: "**/go.sum"
      - name: Setup Swagger
        run: |
          go install github.com/swaggo/swag/cmd/swag@v1.16.2
          swag init -g cmd/service/main.go
      - name: Run govulncheck
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@v1.1.3
          govulncheck -C . -format text ./...
